// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: norikv.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Kv_Put_FullMethodName    = "/norikv.v1.Kv/Put"
	Kv_Get_FullMethodName    = "/norikv.v1.Kv/Get"
	Kv_Delete_FullMethodName = "/norikv.v1.Kv/Delete"
)

// KvClient is the client API for Kv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KvClient interface {
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type kvClient struct {
	cc grpc.ClientConnInterface
}

func NewKvClient(cc grpc.ClientConnInterface) KvClient {
	return &kvClient{cc}
}

func (c *kvClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, Kv_Put_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, Kv_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, Kv_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KvServer is the server API for Kv service.
// All implementations must embed UnimplementedKvServer
// for forward compatibility
type KvServer interface {
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	mustEmbedUnimplementedKvServer()
}

// UnimplementedKvServer must be embedded to have forward compatible implementations.
type UnimplementedKvServer struct {
}

func (UnimplementedKvServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedKvServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedKvServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedKvServer) mustEmbedUnimplementedKvServer() {}

// UnsafeKvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KvServer will
// result in compilation errors.
type UnsafeKvServer interface {
	mustEmbedUnimplementedKvServer()
}

func RegisterKvServer(s grpc.ServiceRegistrar, srv KvServer) {
	s.RegisterService(&Kv_ServiceDesc, srv)
}

func _Kv_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kv_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kv_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kv_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kv_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kv_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Kv_ServiceDesc is the grpc.ServiceDesc for Kv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Kv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "norikv.v1.Kv",
	HandlerType: (*KvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _Kv_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Kv_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Kv_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "norikv.proto",
}

const (
	Meta_WatchCluster_FullMethodName = "/norikv.v1.Meta/WatchCluster"
)

// MetaClient is the client API for Meta service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetaClient interface {
	WatchCluster(ctx context.Context, in *ClusterView, opts ...grpc.CallOption) (Meta_WatchClusterClient, error)
}

type metaClient struct {
	cc grpc.ClientConnInterface
}

func NewMetaClient(cc grpc.ClientConnInterface) MetaClient {
	return &metaClient{cc}
}

func (c *metaClient) WatchCluster(ctx context.Context, in *ClusterView, opts ...grpc.CallOption) (Meta_WatchClusterClient, error) {
	stream, err := c.cc.NewStream(ctx, &Meta_ServiceDesc.Streams[0], Meta_WatchCluster_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &metaWatchClusterClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Meta_WatchClusterClient interface {
	Recv() (*ClusterView, error)
	grpc.ClientStream
}

type metaWatchClusterClient struct {
	grpc.ClientStream
}

func (x *metaWatchClusterClient) Recv() (*ClusterView, error) {
	m := new(ClusterView)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MetaServer is the server API for Meta service.
// All implementations must embed UnimplementedMetaServer
// for forward compatibility
type MetaServer interface {
	WatchCluster(*ClusterView, Meta_WatchClusterServer) error
	mustEmbedUnimplementedMetaServer()
}

// UnimplementedMetaServer must be embedded to have forward compatible implementations.
type UnimplementedMetaServer struct {
}

func (UnimplementedMetaServer) WatchCluster(*ClusterView, Meta_WatchClusterServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchCluster not implemented")
}
func (UnimplementedMetaServer) mustEmbedUnimplementedMetaServer() {}

// UnsafeMetaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetaServer will
// result in compilation errors.
type UnsafeMetaServer interface {
	mustEmbedUnimplementedMetaServer()
}

func RegisterMetaServer(s grpc.ServiceRegistrar, srv MetaServer) {
	s.RegisterService(&Meta_ServiceDesc, srv)
}

func _Meta_WatchCluster_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClusterView)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetaServer).WatchCluster(m, &metaWatchClusterServer{stream})
}

type Meta_WatchClusterServer interface {
	Send(*ClusterView) error
	grpc.ServerStream
}

type metaWatchClusterServer struct {
	grpc.ServerStream
}

func (x *metaWatchClusterServer) Send(m *ClusterView) error {
	return x.ServerStream.SendMsg(m)
}

// Meta_ServiceDesc is the grpc.ServiceDesc for Meta service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Meta_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "norikv.v1.Meta",
	HandlerType: (*MetaServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchCluster",
			Handler:       _Meta_WatchCluster_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "norikv.proto",
}

const (
	Admin_TransferShard_FullMethodName = "/norikv.v1.Admin/TransferShard"
	Admin_SnapshotShard_FullMethodName = "/norikv.v1.Admin/SnapshotShard"
)

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminClient interface {
	TransferShard(ctx context.Context, in *ShardInfo, opts ...grpc.CallOption) (*ShardInfo, error)
	SnapshotShard(ctx context.Context, in *ShardInfo, opts ...grpc.CallOption) (*ShardInfo, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) TransferShard(ctx context.Context, in *ShardInfo, opts ...grpc.CallOption) (*ShardInfo, error) {
	out := new(ShardInfo)
	err := c.cc.Invoke(ctx, Admin_TransferShard_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) SnapshotShard(ctx context.Context, in *ShardInfo, opts ...grpc.CallOption) (*ShardInfo, error) {
	out := new(ShardInfo)
	err := c.cc.Invoke(ctx, Admin_SnapshotShard_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility
type AdminServer interface {
	TransferShard(context.Context, *ShardInfo) (*ShardInfo, error)
	SnapshotShard(context.Context, *ShardInfo) (*ShardInfo, error)
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have forward compatible implementations.
type UnimplementedAdminServer struct {
}

func (UnimplementedAdminServer) TransferShard(context.Context, *ShardInfo) (*ShardInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferShard not implemented")
}
func (UnimplementedAdminServer) SnapshotShard(context.Context, *ShardInfo) (*ShardInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SnapshotShard not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_TransferShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShardInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).TransferShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_TransferShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).TransferShard(ctx, req.(*ShardInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_SnapshotShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShardInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).SnapshotShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_SnapshotShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).SnapshotShard(ctx, req.(*ShardInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "norikv.v1.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransferShard",
			Handler:    _Admin_TransferShard_Handler,
		},
		{
			MethodName: "SnapshotShard",
			Handler:    _Admin_SnapshotShard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "norikv.proto",
}

const (
	Raft_RequestVote_FullMethodName     = "/norikv.v1.Raft/RequestVote"
	Raft_AppendEntries_FullMethodName   = "/norikv.v1.Raft/AppendEntries"
	Raft_InstallSnapshot_FullMethodName = "/norikv.v1.Raft/InstallSnapshot"
	Raft_ReadIndex_FullMethodName       = "/norikv.v1.Raft/ReadIndex"
)

// RaftClient is the client API for Raft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftClient interface {
	RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error)
	AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error)
	InstallSnapshot(ctx context.Context, in *InstallSnapshotRequest, opts ...grpc.CallOption) (*InstallSnapshotResponse, error)
	ReadIndex(ctx context.Context, in *ReadIndexRequest, opts ...grpc.CallOption) (*ReadIndexResponse, error)
}

type raftClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftClient(cc grpc.ClientConnInterface) RaftClient {
	return &raftClient{cc}
}

func (c *raftClient) RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error) {
	out := new(RequestVoteResponse)
	err := c.cc.Invoke(ctx, Raft_RequestVote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error) {
	out := new(AppendEntriesResponse)
	err := c.cc.Invoke(ctx, Raft_AppendEntries_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) InstallSnapshot(ctx context.Context, in *InstallSnapshotRequest, opts ...grpc.CallOption) (*InstallSnapshotResponse, error) {
	out := new(InstallSnapshotResponse)
	err := c.cc.Invoke(ctx, Raft_InstallSnapshot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) ReadIndex(ctx context.Context, in *ReadIndexRequest, opts ...grpc.CallOption) (*ReadIndexResponse, error) {
	out := new(ReadIndexResponse)
	err := c.cc.Invoke(ctx, Raft_ReadIndex_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftServer is the server API for Raft service.
// All implementations must embed UnimplementedRaftServer
// for forward compatibility
type RaftServer interface {
	RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteResponse, error)
	AppendEntries(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error)
	InstallSnapshot(context.Context, *InstallSnapshotRequest) (*InstallSnapshotResponse, error)
	ReadIndex(context.Context, *ReadIndexRequest) (*ReadIndexResponse, error)
	mustEmbedUnimplementedRaftServer()
}

// UnimplementedRaftServer must be embedded to have forward compatible implementations.
type UnimplementedRaftServer struct {
}

func (UnimplementedRaftServer) RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVote not implemented")
}
func (UnimplementedRaftServer) AppendEntries(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendEntries not implemented")
}
func (UnimplementedRaftServer) InstallSnapshot(context.Context, *InstallSnapshotRequest) (*InstallSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstallSnapshot not implemented")
}
func (UnimplementedRaftServer) ReadIndex(context.Context, *ReadIndexRequest) (*ReadIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadIndex not implemented")
}
func (UnimplementedRaftServer) mustEmbedUnimplementedRaftServer() {}

// UnsafeRaftServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftServer will
// result in compilation errors.
type UnsafeRaftServer interface {
	mustEmbedUnimplementedRaftServer()
}

func RegisterRaftServer(s grpc.ServiceRegistrar, srv RaftServer) {
	s.RegisterService(&Raft_ServiceDesc, srv)
}

func _Raft_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raft_RequestVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).RequestVote(ctx, req.(*RequestVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raft_AppendEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).AppendEntries(ctx, req.(*AppendEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_InstallSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).InstallSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raft_InstallSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).InstallSnapshot(ctx, req.(*InstallSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_ReadIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).ReadIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raft_ReadIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).ReadIndex(ctx, req.(*ReadIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Raft_ServiceDesc is the grpc.ServiceDesc for Raft service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Raft_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "norikv.v1.Raft",
	HandlerType: (*RaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestVote",
			Handler:    _Raft_RequestVote_Handler,
		},
		{
			MethodName: "AppendEntries",
			Handler:    _Raft_AppendEntries_Handler,
		},
		{
			MethodName: "InstallSnapshot",
			Handler:    _Raft_InstallSnapshot_Handler,
		},
		{
			MethodName: "ReadIndex",
			Handler:    _Raft_ReadIndex_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "norikv.proto",
}

const (
	Vector_CreateIndex_FullMethodName = "/norikv.v1.Vector/CreateIndex"
	Vector_DropIndex_FullMethodName   = "/norikv.v1.Vector/DropIndex"
	Vector_Insert_FullMethodName      = "/norikv.v1.Vector/Insert"
	Vector_Delete_FullMethodName      = "/norikv.v1.Vector/Delete"
	Vector_Search_FullMethodName      = "/norikv.v1.Vector/Search"
	Vector_Get_FullMethodName         = "/norikv.v1.Vector/Get"
)

// VectorClient is the client API for Vector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VectorClient interface {
	CreateIndex(ctx context.Context, in *CreateVectorIndexRequest, opts ...grpc.CallOption) (*CreateVectorIndexResponse, error)
	DropIndex(ctx context.Context, in *DropVectorIndexRequest, opts ...grpc.CallOption) (*DropVectorIndexResponse, error)
	Insert(ctx context.Context, in *VectorInsertRequest, opts ...grpc.CallOption) (*VectorInsertResponse, error)
	Delete(ctx context.Context, in *VectorDeleteRequest, opts ...grpc.CallOption) (*VectorDeleteResponse, error)
	Search(ctx context.Context, in *VectorSearchRequest, opts ...grpc.CallOption) (*VectorSearchResponse, error)
	Get(ctx context.Context, in *VectorGetRequest, opts ...grpc.CallOption) (*VectorGetResponse, error)
}

type vectorClient struct {
	cc grpc.ClientConnInterface
}

func NewVectorClient(cc grpc.ClientConnInterface) VectorClient {
	return &vectorClient{cc}
}

func (c *vectorClient) CreateIndex(ctx context.Context, in *CreateVectorIndexRequest, opts ...grpc.CallOption) (*CreateVectorIndexResponse, error) {
	out := new(CreateVectorIndexResponse)
	err := c.cc.Invoke(ctx, Vector_CreateIndex_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorClient) DropIndex(ctx context.Context, in *DropVectorIndexRequest, opts ...grpc.CallOption) (*DropVectorIndexResponse, error) {
	out := new(DropVectorIndexResponse)
	err := c.cc.Invoke(ctx, Vector_DropIndex_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorClient) Insert(ctx context.Context, in *VectorInsertRequest, opts ...grpc.CallOption) (*VectorInsertResponse, error) {
	out := new(VectorInsertResponse)
	err := c.cc.Invoke(ctx, Vector_Insert_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorClient) Delete(ctx context.Context, in *VectorDeleteRequest, opts ...grpc.CallOption) (*VectorDeleteResponse, error) {
	out := new(VectorDeleteResponse)
	err := c.cc.Invoke(ctx, Vector_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorClient) Search(ctx context.Context, in *VectorSearchRequest, opts ...grpc.CallOption) (*VectorSearchResponse, error) {
	out := new(VectorSearchResponse)
	err := c.cc.Invoke(ctx, Vector_Search_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorClient) Get(ctx context.Context, in *VectorGetRequest, opts ...grpc.CallOption) (*VectorGetResponse, error) {
	out := new(VectorGetResponse)
	err := c.cc.Invoke(ctx, Vector_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VectorServer is the server API for Vector service.
// All implementations must embed UnimplementedVectorServer
// for forward compatibility
type VectorServer interface {
	CreateIndex(context.Context, *CreateVectorIndexRequest) (*CreateVectorIndexResponse, error)
	DropIndex(context.Context, *DropVectorIndexRequest) (*DropVectorIndexResponse, error)
	Insert(context.Context, *VectorInsertRequest) (*VectorInsertResponse, error)
	Delete(context.Context, *VectorDeleteRequest) (*VectorDeleteResponse, error)
	Search(context.Context, *VectorSearchRequest) (*VectorSearchResponse, error)
	Get(context.Context, *VectorGetRequest) (*VectorGetResponse, error)
	mustEmbedUnimplementedVectorServer()
}

// UnimplementedVectorServer must be embedded to have forward compatible implementations.
type UnimplementedVectorServer struct {
}

func (UnimplementedVectorServer) CreateIndex(context.Context, *CreateVectorIndexRequest) (*CreateVectorIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIndex not implemented")
}
func (UnimplementedVectorServer) DropIndex(context.Context, *DropVectorIndexRequest) (*DropVectorIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropIndex not implemented")
}
func (UnimplementedVectorServer) Insert(context.Context, *VectorInsertRequest) (*VectorInsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedVectorServer) Delete(context.Context, *VectorDeleteRequest) (*VectorDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedVectorServer) Search(context.Context, *VectorSearchRequest) (*VectorSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedVectorServer) Get(context.Context, *VectorGetRequest) (*VectorGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedVectorServer) mustEmbedUnimplementedVectorServer() {}

// UnsafeVectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VectorServer will
// result in compilation errors.
type UnsafeVectorServer interface {
	mustEmbedUnimplementedVectorServer()
}

func RegisterVectorServer(s grpc.ServiceRegistrar, srv VectorServer) {
	s.RegisterService(&Vector_ServiceDesc, srv)
}

func _Vector_CreateIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVectorIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServer).CreateIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vector_CreateIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServer).CreateIndex(ctx, req.(*CreateVectorIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vector_DropIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropVectorIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServer).DropIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vector_DropIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServer).DropIndex(ctx, req.(*DropVectorIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vector_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorInsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vector_Insert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServer).Insert(ctx, req.(*VectorInsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vector_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vector_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServer).Delete(ctx, req.(*VectorDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vector_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vector_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServer).Search(ctx, req.(*VectorSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vector_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vector_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServer).Get(ctx, req.(*VectorGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Vector_ServiceDesc is the grpc.ServiceDesc for Vector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Vector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "norikv.v1.Vector",
	HandlerType: (*VectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateIndex",
			Handler:    _Vector_CreateIndex_Handler,
		},
		{
			MethodName: "DropIndex",
			Handler:    _Vector_DropIndex_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _Vector_Insert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Vector_Delete_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Vector_Search_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Vector_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "norikv.proto",
}
